name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest joblib requests

      - name: Lint (basic)
        run: python -m py_compile $(git ls-files '*.py')

      - name: Unit tests
        run: pytest -q

      - name: Quick training smoke (v0.1)
        run: python model/train_v01.py | tee metrics.txt

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics-v01
          path: |
            model/metrics_v01.json
            metrics.txt
